title: Challengesof minorities 
author:YOUNIS M00AL 
email: younismood@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Challenges facing minorities in the 21st century 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepag
